domain_path: /home/xilinx/Projects/soc_project_stereo_matching/ZedBoard/Vitis/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
