domain_path: /home/xilinx/Projects/stere_matching_software/vitis_software/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
