domain_path: /home/xilinx/Projects/old/stere_matching_software/vitis/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/lwip_tcp_perf_client
template: lwip_tcp_perf_client
lang: c
